# Generated by Django 5.2.17 on 2026-09-27 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('summary', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('repo_url', models.URLField(blank=True, default='', max_length=1024)),
                ('demo_video_url', models.URLField(blank=True, default='', max_length=1024)),
                ('live_url', models.URLField(blank=True, default='', max_length=1024)),
                ('tech_tags', models.JSONField(blank=True, default=list)),
                ('custom_answers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('duplicate_flag_reason', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='events.event')),
                ('is_duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='submissions.project')),
            ],
            options={
                'db_table': 'submissions_project',
            },
        ),
    ]
