# Generated by Django 5.2.17 on 2026-09-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duplicate_override',
            field=models.BooleanField(default=False),
        ),
    ]
