# Generated by Django 5.2.17 on 2026-09-28 23:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_voting_settings'),
        ('submissions', '0003_project_duplicate_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('OPEN', 'Open link'), ('AUTH', 'Authenticated user')], max_length=8)),
                ('voter_fingerprint', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voting_comments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='submissions.project')),
            ],
            options={
                'db_table': 'voting_comment',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VoteAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('OPEN', 'Open link'), ('AUTH', 'Authenticated user')], max_length=8)),
                ('voter_fingerprint', models.CharField(max_length=128)),
                ('outcome', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED_DUPLICATE', 'Duplicate'), ('REJECTED_RATE_LIMIT', 'Rate limited'), ('REJECTED_CLOSED', 'Voting closed'), ('REJECTED_BUDGET', 'Vote budget exhausted'), ('WITHDRAWN', 'Withdrawn')], max_length=32)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vote_attempts', to='events.event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vote_attempts', to='submissions.project')),
            ],
            options={
                'db_table': 'voting_voteattempt',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('OPEN', 'Open link'), ('AUTH', 'Authenticated user')], max_length=8)),
                ('voter_fingerprint', models.CharField(max_length=128)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='events.event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='submissions.project')),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_votes', to='voting.voteattempt')),
            ],
            options={
                'db_table': 'voting_vote',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='voteattempt',
            index=models.Index(fields=['voter_fingerprint', 'created_at'], name='vote_attempt_fingerprint_time'),
        ),
        migrations.AddIndex(
            model_name='voteattempt',
            index=models.Index(fields=['event', 'mode', 'voter_fingerprint', 'created_at'], name='vote_attempt_rate_lookup'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('event', 'project', 'mode', 'voter_fingerprint'), name='uniq_vote_event_project_mode_fingerprint'),
        ),
    ]
