# Generated by Django 5.2.17 on 2026-09-27 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('events', '0002_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeTrackEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_eligibilities', to='accounts.eventmembership')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_eligibilities', to='events.track')),
            ],
            options={
                'db_table': 'accounts_judgetrackeligibility',
                'constraints': [models.UniqueConstraint(fields=('event_membership', 'track'), name='unique_judge_track')],
            },
        ),
    ]
