# Generated by Django 5.2.17 on 2026-09-29 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_judgetrackeligibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'accounts_authattempt',
                'indexes': [models.Index(fields=['ip_hash', 'action', 'created_at'], name='accounts_au_ip_hash_da797c_idx')],
            },
        ),
    ]
