# Generated by Django 5.2.17 on 2026-09-28
from django.db import migrations, models


def mark_fixture_event_current(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    db_alias = schema_editor.connection.alias
    # Prioritize fixture event evt_01, fallback to first event if any exist
    event = Event.objects.using(db_alias).filter(external_id='evt_01').first()
    if event is None:
        event = Event.objects.using(db_alias).first()
    if event is not None:
        event.is_current = True
        event.save(update_fields=['is_current'])


def unmark_fixture_event_current(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    db_alias = schema_editor.connection.alias
    Event.objects.using(db_alias).filter(is_current=True).update(is_current=False)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(
                condition=models.Q(is_current=True),
                fields=('is_current',),
                name='unique_current_event',
            ),
        ),
        migrations.RunPython(
            mark_fixture_event_current,
            unmark_fixture_event_current,
        ),
    ]
