# Generated by Django 5.2.17 on 2026-09-27 17:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_prize'),
        ('submissions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=16)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='events.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='submissions.project')),
            ],
            options={
                'db_table': 'judging_judgeassignment',
            },
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ballot', to='judging.judgeassignment')),
            ],
            options={
                'db_table': 'judging_ballot',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='events.event')),
            ],
            options={
                'db_table': 'judging_rubric',
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ('max_score', models.DecimalField(decimal_places=2, default=5, max_digits=8)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='judging.rubric')),
            ],
            options={
                'db_table': 'judging_rubriccriterion',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BallotScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='judging.ballot')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballot_scores', to='judging.rubriccriterion')),
            ],
            options={
                'db_table': 'judging_ballotscore',
            },
        ),
        migrations.AddConstraint(
            model_name='judgeassignment',
            constraint=models.UniqueConstraint(fields=('judge', 'project'), name='uniq_judge_project_assignment'),
        ),
        migrations.AddConstraint(
            model_name='rubric',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='uniq_rubric_event_name'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.UniqueConstraint(fields=('rubric', 'name'), name='uniq_criterion_rubric_name'),
        ),
        migrations.AddConstraint(
            model_name='ballotscore',
            constraint=models.UniqueConstraint(fields=('ballot', 'criterion'), name='uniq_ballot_criterion_score'),
        ),
    ]
