# Generated by Django 5.2.17 on 2026-09-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_prize'),
        ('judging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rubric',
            name='uniq_rubric_event_name',
        ),
        migrations.AddConstraint(
            model_name='rubric',
            constraint=models.UniqueConstraint(fields=('event',), name='uniq_rubric_per_event'),
        ),
    ]
