# Generated by Django 5.2.17 on 2026-09-27 20:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_prize'),
        ('judging', '0002_remove_rubric_uniq_rubric_event_name_and_more'),
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('method_name', models.CharField(max_length=128)),
                ('parameters', models.JSONField(default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalization_runs', to='events.event')),
            ],
            options={
                'db_table': 'judging_normalizationrun',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_mean', models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True)),
                ('normalized_mean', models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('judge_graph_component_id', models.PositiveIntegerField(blank=True, null=True)),
                ('judge_graph_fiedler_value', models.FloatField(blank=True, null=True)),
                ('rank_ci_low', models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True)),
                ('rank_ci_high', models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_scores', to='submissions.project')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='judging.normalizationrun')),
            ],
            options={
                'db_table': 'judging_normalizedscore',
                'ordering': ['project_id'],
                'constraints': [models.UniqueConstraint(fields=('run', 'project'), name='uniq_normalized_score_run_project')],
            },
        ),
    ]
