# Generated by Django 5.2.17 on 2026-09-27 20:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_prize'),
        ('judging', '0003_normalizationrun_normalizedscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_k', models.PositiveIntegerField()),
                ('seed', models.BigIntegerField()),
                ('under_coverage', models.JSONField(default=list)),
                ('connectivity_report', models.JSONField(default=dict)),
                ('anchor_injections', models.JSONField(default=list)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_runs', to='events.event')),
            ],
            options={
                'db_table': 'judging_assignmentrun',
                'ordering': ['id'],
            },
        ),
    ]
