# Generated by Django 5.2.17 on 2026-09-28 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


GENESIS_HASH = '0' * 64


def create_initial_head(apps, schema_editor):
    Head = apps.get_model('audit', 'AuditChainHead')
    Head.objects.using(schema_editor.connection.alias).get_or_create(
        pk=1, defaults={'seq': 0, 'head_hash': GENESIS_HASH},
    )


def remove_initial_head(apps, schema_editor):
    Head = apps.get_model('audit', 'AuditChainHead')
    Head.objects.using(schema_editor.connection.alias).filter(pk=1, seq=0).delete()


class PostgreSQLRunSQL(migrations.RunSQL):
    """Apply trigger SQL only when the active database is PostgreSQL."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChainHead',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('seq', models.BigIntegerField(default=0)),
                ('head_hash', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'audit_auditchainhead',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='audit_chain_head_singleton')],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('seq', models.BigIntegerField(primary_key=True, serialize=False)),
                ('actor_label', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('target_type', models.CharField(max_length=255)),
                ('target_id', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.CharField(max_length=40)),
                ('prev_hash', models.CharField(max_length=64)),
                ('entry_hash', models.CharField(max_length=64)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_auditlogentry',
                'ordering': ['seq'],
            },
        ),
        migrations.RunPython(create_initial_head, remove_initial_head),
        PostgreSQLRunSQL(
            sql='''
                CREATE FUNCTION audit_reject_immutable_mutation() RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'audit log entries are immutable';
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER audit_log_entry_no_row_mutation
                BEFORE UPDATE OR DELETE ON audit_auditlogentry
                FOR EACH ROW EXECUTE FUNCTION audit_reject_immutable_mutation();
                CREATE TRIGGER audit_log_entry_no_truncate
                BEFORE TRUNCATE ON audit_auditlogentry
                FOR EACH STATEMENT EXECUTE FUNCTION audit_reject_immutable_mutation();
            ''',
            reverse_sql='''
                DROP TRIGGER IF EXISTS audit_log_entry_no_truncate ON audit_auditlogentry;
                DROP TRIGGER IF EXISTS audit_log_entry_no_row_mutation ON audit_auditlogentry;
                DROP FUNCTION IF EXISTS audit_reject_immutable_mutation();
            ''',
        ),
    ]
